version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: NODE_ENV=development npm install
      - save_cache:
          name: Save cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Unit testing
          command: npm test
      - run:
          name: Linter
          command: npm run lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - unit-test
